spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: FuZhiLong2017@
    url: jdbc:mysql://192.168.1.106:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell


